{% set name = "scvi-tools" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30f2248adcd210e2b239b1601d33d47f6676ace99896bcf9593921f90d199bd4

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python >=3.7
    - poetry >=1.0.9
    - poetry-core
    - pip >=19.0
  run:
    - python >=3.7
    - anndata >=0.7.5
    - docrep >=0.3.2
    - h5py >=2.9.0
    - importlib_metadata
    - ipywidgets >=7.5.1
    - numpy >=1.17.0
    - openpyxl >=3.0
    - pandas >=1.0
    - pyro-ppl >=1.6.0
    - pytorch-lightning >=1.5,<1.6
    - rich >=9.12.4
    - scikit-learn >=0.21.2
    - pytorch >=1.8.0
    - tqdm >=4.56.0
    - jax >=0.3.0
    - jaxlib >=0.3.0
    - optax
    - numpyro >=0.9.0
    - flax >=0.4.0
    - torchmetrics >=0.6.0

test:
  imports:
    - scvi
    - scvi.model
    - scvi.nn
    - scvi.train
    - scvi.external
    - scvi.dataloaders
    - scvi.data
    - scvi.distributions
  requires:
    - pytest

about:
  home: https://scvi-tools.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deep probabilistic analysis of single-cell omics data.
  doc_url: https://docs.scvi-tools.org/en/stable/
  dev_url: https://github.com/YosefLab/scvi-tools

extra:
  recipe-maintainers:
    - romain-lopez
    - adamgayoso
    - galenxing
    - jjhong922
    - watiss
